### ISSUE TITLE
Links in README lead to 404

### ISSUE THREAD

**Issue by GenieTim** [bluora/php-slack-api#2]
I open this issue before a PR in order to find out, whether this repo is a maintained version of https://github.com/cleentfaar/slack? 

If so, I intend to open a PR if you care with the following changes:

- [x] fix links in README
- [x] enable upgrade to Symfony 4 (symfony-yaml)

Also, while we are at it, the [instructions](https://github.com/hnhdigital-os/php-slack-api/blob/master/src/Resources/doc/installation.md) regarding composer would have to be updated – did you publish it anyways?

**Comment by RoccoHoward** [comment]
Hello @BernhardWebstudio ,

Yes, It's a maintained repo - so welcome PR's + I will deal with them fairly quickly so you won't have to wait around.

The instructions are published @ https://hnhdigital-os.github.io/php-slack-api/ - so will probably be a good idea to do the changes - especially if we maintain this repo.

Also, I did start working on a new version that covered all of Slack's API - https://github.com/hnhdigital-os/php-slack-api-1 if you wanted to check it out. It needs a bit more work still though - I just haven't needed Slack in any new projects, but do plan to come around to this one again.

**Comment by RoccoHoward** [comment]
Great work. I made some further changes and tests pass in php versions 7.1 and 7.2
